#!/usr/bin/env bash
set -eu -o pipefail
shopt -s extglob

cd $(dirname "${BASH_SOURCE[0]}")

for file in !(DarkPastel.terminal|fish|install|README.md|chisel|pep8); do
  target="${HOME}/.${file}"
  ln -fhs "$PWD/$file" "$target" &>/dev/null && echo "linking $file"
done

mkdir -p "$HOME/.config/fish"
for file in fish/*; do
  base=${file##*/}
  ln -fhs "$PWD/$file" "$HOME/.config/fish/$base" &>/dev/null && echo "linking .config/fish/$base"
done

mkdir -p "$HOME/.config"
ln -fhs "$PWD/pep8" "$HOME/.config/pep8" &>/dev/null && echo "linking .config/pep8"
