#!/usr/bin/env bash
set -eu -o pipefail
shopt -s extglob

cd $(dirname "${BASH_SOURCE[0]}")

for file in !(fish|install|README.md|chisel|xctemplate); do
  target="${HOME}/.${file}"
  ln -s "$(pwd)/$file" "$target" &>/dev/null && echo "linking $file"
done

mkdir -p "$HOME/.config/fish"
for file in fish/*; do
  base=${file##*/}
  ln -s "$(pwd)/$file" "$HOME/.config/fish/$base" &>/dev/null && echo "linking .config/fish/$base"
done

mkdir -p ~/Library/Developer/Xcode/Templates/Custom

for dir in xctemplate/*; do
  cp -R "$dir" ~/Library/Developer/Xcode/Templates/Custom/ &>/dev/null && echo "copying ${dir##*/}"
done
